blueprint:
  name: Single Battery Sensor Low Notification
  description: >
    Monitors one battery sensor and sends a customizable notification when its
    percentage falls below a threshold.  
    Lets you pick an icon visually or define a Jinja template if desired.
  domain: automation

  input:
    battery_sensor:
      name: Battery Sensor
      description: The battery level sensor to monitor.
      selector:
        entity:
          domain: sensor

    notify_devices:
      name: Notification Targets
      description: Devices or notify services to receive the alert.
      selector:
        device:
          multiple: true
          integration: mobile_app

    battery_threshold:
      name: Battery Threshold
      description: Notify when battery drops below this value.
      default: 25
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    message_template:
      name: Message Template
      description: >
        Jinja template for the notification message.  
        Variable: `entity` (the selected battery sensor).  
        Example: "{{ state_attr(entity, 'friendly_name') }} is at {{ states(entity) }}% battery."
      default: "{{ state_attr(entity, 'friendly_name') }} is at {{ states(entity) }}% battery."
      selector:
        text:

    icon:
      name: Notification Icon
      description: >
        Pick an icon for the notification.  
        (Optional: leave empty if you want to use a dynamic Jinja template below.)
      default: mdi:battery-alert
      selector:
        icon:

    dynamic_icon_template:
      name: Dynamic Icon Template (optional)
      description: >
        Optional Jinja template for dynamic icons.  
        Example: "{{ 'mdi:battery-alert' if (states(entity) | int < 15) else 'mdi:battery-50' }}"
      default: ""
      selector:
        text:

    check_interval:
      name: Check Interval (minutes)
      description: How often to check the battery level.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: "min"
          mode: slider

mode: restart
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: "/{{ check_interval }}"

variables:
  entity: !input battery_sensor
  threshold: !input battery_threshold
  message_template: !input message_template
  icon_static: !input icon
  icon_dynamic_template: !input dynamic_icon_template

condition:
  - condition: template
    value_template: "{{ states(entity) is number and (states(entity) | int) <= threshold }}"

action:
  - variables:
      message: "{{ message_template }}"
      icon: >
        {% if icon_dynamic_template %}
          {{ icon_dynamic_template }}
        {% else %}
          {{ icon_static }}
        {% endif %}
  - repeat:
      for_each: !input notify_devices
      sequence:
        - service: notify.send_message
          data:
            target: "{{ device_attr(repeat.item, 'name') }}"
            title: "Low Battery Alert"
            message: "{{ message }}"
            data:
              icon: "{{ icon }}"
